= Tableau des médailles

[vega]
....
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "description": "Tableau des médailles des JO 2020",
  "width": 500,
  "height": 500,
  "padding": 5,

  "data": [
    {
      "name": "table",
      "values": [
        {"country": "🇺🇸", "position": "0", "number": 39, "v": "#FFD700"},
        {"country": "🇺🇸", "position": "1", "number": 41, "v": "#C0C0C0"},
        {"country": "🇺🇸", "position": "2", "number": 33, "v": "#614e1a"},
        {"country": "🇨🇳", "position": "0", "number": 38, "v": "#FFD700"},
        {"country": "🇨🇳", "position": "1", "number": 32, "v": "#C0C0C0"},
        {"country": "🇨🇳", "position": "2", "number": 19, "v": "#614e1a"},
        {"country": "🇯🇵", "position": "0", "number": 27, "v": "#FFD700"},
        {"country": "🇯🇵", "position": "1", "number": 14, "v": "#C0C0C0"},
        {"country": "🇯🇵", "position": "2", "number": 17, "v": "#614e1a"},
        {"country": "🇫🇷", "position": "0", "number": 10, "v": "#FFD700"},
        {"country": "🇫🇷", "position": "1", "number": 12, "v": "#C0C0C0"},
        {"country": "🇫🇷", "position": "2", "number": 11, "v": "#614e1a"}
      ]
    }
  ],

  "scales": [
    {
      "name": "yscale",
      "type": "band",
      "domain": {"data": "table", "field": "country"},
      "range": "height",
      "padding": 0.2
    },
    {
      "name": "xscale",
      "type": "linear",
      "domain": {"data": "table", "field": "number"},
      "range": "width",
      "round": true,
      "zero": true,
      "nice": true
    },
    {
      "name": "color",
      "type": "ordinal",
      "domain": {"data": "table", "field": "position"},
      "range": {"scheme": "category20"}
    }
  ],

  "axes": [
    {"orient": "left", "scale": "yscale", "tickSize": 0, "labelPadding": 12, "zindex": 1, "labelFontSize": 32},
    {"orient": "bottom", "scale": "xscale"}
  ],

  "marks": [
    {
      "type": "group",

      "from": {
        "facet": {
          "data": "table",
          "name": "facet",
          "groupby": "country"
        }
      },

      "encode": {
        "enter": {
          "y": {"scale": "yscale", "field": "country"}
        }
      },

      "signals": [
        {"name": "height", "update": "bandwidth('yscale')"}
      ],

      "scales": [
        {
          "name": "pos",
          "type": "band",
          "range": "height",
          "domain": {"data": "facet", "field": "position"}
        }
      ],

      "marks": [
        {
          "name": "bars",
          "from": {"data": "facet"},
          "type": "rect",
          "encode": {
            "enter": {
              "y": {"scale": "pos", "field": "position"},
              "height": {"scale": "pos", "band": 1},
              "x": {"scale": "xscale", "field": "number"},
              "x2": {"scale": "xscale", "value": 0},
              "fill": { "field": "v"}
            }
          }
        },
        {
          "type": "text",
          "from": {"data": "bars"},
          "encode": {
            "enter": {
              "x": {"field": "x2", "offset": -5},
              "y": {"field": "y", "offset": {"field": "height", "mult": 0.5}},
              "fill": [
                {"test": "contrast('white', datum.fill) > contrast('black', datum.fill)", "value": "white"},
                {"value": "black"}
              ],
              "align": {"value": "right"},
              "baseline": {"value": "middle"},
              "text": {"field": "datum.number"}
            }
          }
        }
      ]
    }
  ]
}
....
