= Sélection de la ville hôte et double attribution des Jeux

Compte tenu des défections successives de Rome, Hambourg et Budapest, et dès le 8 décembre 2016, Thomas Bach, le président
du Comité international olympique, avait réfléchi à une double attribution en expliquant « nous produisons trop de [dossiers] perdants ».
Le 17 mars 2017, il confirme et émet l'hypothèse d'une attribution simultanée des JO 2024 et 2028, afin de conserver les
« deux excellentes candidatures » de Paris et Los Angeles, les deux dernières villes encore en course pour l'édition 2024.
Cette solution assurant donc aux deux villes d'obtenir l'organisation des Jeux olympiques, en 2024 pour l'une, en 2028 pour l'autre.
Le principe de la double attribution était déjà appliqué pour les olympiades de 1896 et 1900 puis celles de 1924 et 1928.
Le 13 mai 2017, le maire de Los Angeles Eric Garcetti se dit favorable à cette proposition, ajoutant : « Je sais que je n'ai
pas une position orthodoxe sur la question et je sais que Paris a pu dire par le passé que c'était 2024 ou rien », n'écartant
pas ainsi l'idée de voir sa ville organiser les JO 2028, afin de laisser à Paris le soin d'organiser ceux de 2024.

Le 9 juin 2017, le bureau exécutif du Comité international olympique adopte à l'unanimité la recommandation du président
Thomas Bach en faveur d'un double vote à Lima le 13 septembre, pour désigner les villes-hôtes des Jeux olympiques 2024 et 2028,
soit Paris et Los Angeles dans un ordre qui reste à définir. Le 11 juillet 2017, lors d'une session extraordinaire à Lausanne
où les deux villes présentent leurs projets, la centaine de membres du CIO approuvent cette décision, sans surprise. Le
31 juillet, le CIO annonce qu'il est parvenu à un accord avec la ville californienne pour qu'elle organise l'édition 2028,
Paris restant seul en lice pour l'organisation des Jeux olympiques de 2024. Le 13 septembre 2017, les membres du CIO votent
à l'unanimité et à main levée en faveur de l'attribution des Jeux d'été 2024 à Paris et de ceux de 2028 à Los Angeles.


== Candidatures abandonnées

* Boston est sélectionnée le 8 janvier 2015, mais faute de soutien populaire et après le refus de son maire, la ville renonce
au projet et est remplacée par Los Angeles le 27 juillet 2015.
* Hambourg est présentée comme candidate officiellement le 16 mars 2015 mais, à la suite d'un référendum auprès de la population
le 29 novembre 2015 donnant une majorité à l'opposition à la candidature, la ville se retire.
* Rome, candidate officielle du 2 juillet 2015 au 21 septembre 2016. Toutefois, le Comité olympique national italien dépose
la 2e partie du dossier de candidature auprès du CIO le 7 octobre puis la candidature est retirée le 11 octobre 2016.
* Budapest, candidature retirée le 22 février 2017, par le conseil municipal, à la suite de la campagne du mouvement de jeunes militants,
« Momentum », qui revendique la collecte de 300 000 signatures contre la candidature, soit presque le double du total nécessaire
pour déclencher l'organisation d'un référendum local dans la ville de 1,7 million d'habitants.
* Los Angeles, candidature retirée le 31 juillet 2017, se positionnant pour les Jeux olympiques d'été de 2028.
