= Sports au programme

== Disciplines officielles

Le rugby et le golf, ajoutés au programme des Jeux olympiques de Rio 2016 restant maintenus pour 2020 comme pour 2024, la
liste des 28 sports des Jeux de Paris doit être identique à celle des deux précédentes éditions estivales. Néanmoins,
l'une des mesures de l'Agenda olympique 2020, approuvée fin 2014, déjà appliquée pour les Jeux de Tokyo, laisse aux organisateurs
la possibilité de proposer de nouveaux sports de leur choix, qui doivent ensuite être approuvés par le CIO. Pour Tokyo 2020,
c'est le cas du karaté, du surf, du skateboard, de l'escalade sportive et du baseball/softball. Par ailleurs, la présence
de 28 sports ne définit pas à l'avance la nature ou le nombre des différentes épreuves, ni les éventuels ajouts proposés
par le comité d'organisation, le programme devant être arrêté en juin 2019, lors de la session du CIO qui aura lieu à Lausanne.

La procédure des sports additionnels a lieu début 2019. Il était requis des sports demandant peu d'athlètes, pas d'infrastructures
supplémentaires et populaires auprès des jeunes. Les sports choisis sont le surf, le skateboard, l'escalade, le basket-ball 3x3
et le breakdance. Ces épreuves seraient organisées sur le même site place de la Concorde dans une arène de 35 000 places,
qui devrait aussi accueillir des concerts et des animations. Il n'est pas prévu d'en rajouter d'autres malgré les demandes
répétées du karaté et du squash.

Le 7 décembre 2020, le programme est arrêté par la commission exécutive du CIO. Quatre sports additionnels sont confirmés :
le surf, le skateboard, l'escalade et le breakdance (les trois premiers étant déjà au programme des Jeux de Tokyo précédents).
De plus, plusieurs modifications d'épreuves sont effectuées, entraînant d'une part une réduction du quota d'athlètes nécessaire
pour réduire la complexité d'organisation dans le contexte pandémique, et d'autre part une parité parfaite de ces Jeux avec
autant d'hommes que de femmes engagés :

* en athlétisme, une épreuve de 35 km marche mixte par équipe remplace le 50 km marche hommes en athlétisme ;
* en canoë-kayak, deux épreuves de slalom extrême remplacent deux épreuves de sprint ;
* en boxe, une catégorie féminine prend la place d'une catégorie masculine ;
* en haltérophilie, quatre épreuves sont supprimées ;
* en tir, le skeet par équipes mixtes remplace le trap par équipes mixtes ;
* en voile, le kite en double mixte, le 470 mixte et une troisième épreuve mixte font leur apparition, tandis que le Finn et le 470 hommes et femmes sont supprimés31,32.

Finalement, en voile, le format mixte du kitesurf est abandonné au profit de deux épreuves, masculine et féminine ; la course
au large, un temps imaginée, n'est pas retenue.
